

version: '3'

#Docker Networks
networks:
  laravel:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

# Workflow
services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel/starterapp
    volumes:
      - ./src:/var/www
      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/app.ini
    ports:
      - "9000:9000"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/config/supervisor.conf:/etc/supervisord.conf
      - ./docker/config/nginx.conf:/etc/nginx/sites-enabled/default
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "33060:33060"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - laravel

