

version: '3'

#Docker Networks
networks:
  laravel:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

# Workflow
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lemp/laravel-docker
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "8091:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ewalletdb
      DB_USERNAME: ewallet
      DB_PASSWORD: password
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "33060:33060"
    environment:
      MYSQL_DATABASE: ewalletdb
      MYSQL_USER: ewallet
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - laravel

